# Generated by Django 4.0.2 on 2022-02-21 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_street_alter_city_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('car_number', models.CharField(max_length=16)),
                ('driver_1', models.CharField(blank=True, max_length=32, null=True)),
                ('driver_2', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'route',
                'managed': False,
            },
        ),
    ]
