# Generated by Django 4.0.2 on 2022-02-21 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_route'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avtomat',
            fields=[
                ('avtomat_number', models.AutoField(primary_key=True, serialize=False)),
                ('house', models.CharField(blank=True, max_length=16, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('search_radius', models.IntegerField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('price_for_app', models.IntegerField(blank=True, null=True)),
                ('payment_app_url', models.CharField(blank=True, max_length=64, null=True)),
                ('payment_gateway_url', models.CharField(blank=True, max_length=64, null=True)),
                ('max_sum', models.IntegerField(blank=True, null=True)),
                ('size', models.IntegerField(choices=[(1, 'Single'), (2, 'Double')], default=1)),
                ('competitors', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'avtomat',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='route',
            options={'managed': False, 'ordering': ['name']},
        ),
    ]
